### ISSUE TITLE
一个提议

### ISSUE THREAD

**Issue by zippo88888888** [DyncKathline/FilePicker#5]
我想在 [ZFilerManger](https://github.com/zippo88888888/ZFileManager) 中 表明Java版本的地址就是这个库地址，作者可以吗

**Comment by DyncKathline** [comment]
> 我想在 [ZFilerManger](https://github.com/zippo88888888/ZFileManager) 中 表明Java版本的地址就是这个库地址，作者可以吗

可以的

**Comment by zippo88888888** [comment]
搞定 [笔芯]
